### PR TITLE
Chef Clive's specials

### PR DESCRIPTION
**Pull request by jyanln**
Updated menu at "Concepts of Mathematical Dishes"

### CODE REVIEW

**Comment by tkadur** [comment]
Nice, Mackey would be proud (could use some Diet Pepsi though)
We need your Andrew ID though...

**Comment by tkadur** [comment]
OK

**Comment by jyanln** [comment]
Whoops, my Andrew ID is hanruy. Sorry for that.

**Comment by jbrown215** [comment]
nice

**Pull request closed without merging**
