### PR TITLE
jzhanson

### PR DESCRIPTION
**Pull request by jzhanson**
Like I'm trying to intelligently customize my vim for the things that I want but airline is being stubborn and not looking as nice as I would like

### CODE REVIEW

**Comment by ngupta-iwasaki** [comment]
Everything will be alright josh

**Comment by at-sun** [comment]
i agree ❤️

**Comment by jzhanson** [comment]
thanks guys!!!! Appreciate the sentiment

**Comment by jez** [comment]
🎉

**Comment by jbrown215** [comment]
we r here 4 u josh

**Comment by wilzh40** [comment]
use iterm2 instead of the default terminal.app

**Comment by anbenson** [comment]
👍

**Comment by jzhanson** [comment]
It's funny I finally caved and started using iTerm2 and I don't regret it at all

**Pull request closed without merging**
